### ISSUE TITLE
how to specify results

### ISSUE THREAD

**Issue by gennaro-tedesco** [qwhex/multi_elo#1]
Hi all, I have seen that the Elo implementation of this package presents
```
def calc_s(player1, player2):
    if player1.place < player2.place:
        return 1.0
    if player1.place == player2.place:
        return 0.5
    return 0.0
```
which essentially means that by default it is assumed that players with higher Elo always win against players with lower Elo - which is not necessarily always the case. Would it be possible to specify anywhere a set of results (with corresponding probabilities) to use before updating the new Elo scores? Namely what I am looking for is a way to specify tournament results before re-calculating the new scores.

**Comment by qwhex** [comment]
`player.place` determines who wins.
e.g.
```
player1.place = 1
player2.place = 2
player3.place = 2
```

`player1` wins, and there is a tie for the second place between `player2` and `player3`.

**Comment by qwhex** [comment]
@gennaro-tedesco
Is it clear now? Sorry for the late reply, I didn't notice your message.
I'm happy to help with other questions as well.

**Comment by gennaro-tedesco** [comment]
@qwhex 
yes, thank you. I have tested it and it works fine!

**Comment by qwhex** [comment]
Great to hear :)
